### PR TITLE
Fix LineSpan divide by zero

### PR DESCRIPTION
**Pull request by qiukeren**

### CODE REVIEW

**Comment by maxlandon** [comment]
Great thanks a lot, did this trigger a crash when using some completions ?

**Comment by maxlandon** [comment]
What is the terminal emulator you are using ? And OS/distro ?

**Comment by qiukeren** [comment]
Actually it is a bare-kernel os, the who system is a kernel with a shell (CGO_ENABLED=0)

bare kernel os has no agetty or stty to initilize a tty, so the witdh / height are all 0.

here is the reproduce:

1. use https://github.com/landley/mkroot create a system
2. edit the mkroot.sh , make the /init replace with your own shell
3. run mkroot.sh then change dir to output , run `qemu-*.sh` 

or 

use this https://gitlab.com/qiukeren/oss

1. install qemu bison yacc gcc glibc-static and so on to build the kernel & busybox
2. cd testkvm ;  bash build.sh
3. cd output/host ; bash qemu-x86_64.sh

**Comment by maxlandon** [comment]
Okay will try to check that. 
The problem is solved with your fix ? You still have hints and completions ?

**Comment by qiukeren** [comment]
with this fix, TAB completions is tested ok:

image

but under super long commands can not be detected and wraped

image

this two libraries are also tested
[peterh/liner](https://github.com/peterh/liner) , liner cannot work with TAB and can not  handle long lines
[antirez/linenoise](https://github.com/antirez/linenoise) linenoise works with TAB and can not handle long lines, but have strange problem

**Comment by maxlandon** [comment]
You should use ˋshell.TransientPrintf(msg)` for asynchronously printing your logs, the function is done so that you can keep using the shell and its helpers (completions included) with normal functioning

**Comment by qiukeren** [comment]
here is a update for this issue: 

root cause is /dev/ttyS0 does not provide getWidth, so you will get 0 .

github.com/chzyer/readline 
github.com/abiosoft/ishell
has this issue too, but it presents as: cannot tab to compl. 


busybox can use tab to compl, i guess it fallbacks to fixed size 80 if 0

image

**Pull request merged**
